# Generated by Django 5.0.1 on 2024-01-02 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unicode', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unicode', models.PositiveIntegerField(unique=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('payment', models.CharField(default='', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unicode', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('notes', models.CharField(default='', max_length=500)),
                ('permission', models.JSONField(default=dict)),
                ('hours', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unicode', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unicode', models.PositiveIntegerField(unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('entry', models.CharField(max_length=50)),
                ('notes', models.CharField(default='', max_length=500)),
                ('orders', models.ManyToManyField(to='base.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typecode', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('is_free', models.BooleanField(default=False)),
                ('adjusted_price', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
    ]
