# Generated by Django 4.2.7 on 2024-01-28 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='apt',
            field=models.CharField(default='x', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='unicode',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='unicode',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='unicode',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='unicode',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='unicode',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
