# Generated by Django 4.2.7 on 2024-01-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customer_apt_alter_category_unicode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='base.order'),
        ),
    ]
